# Generated by Django 4.2 on 2023-04-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='size',
            field=models.CharField(max_length=10, verbose_name='사이즈'),
        ),
    ]
